title: Booktypes
description: "Judging book covers by their typography "
footer_text: Copyright 2021 Maud Haugland
header_feature_image: ../uploads/david-van-dijk-3ltht2nxd34-unsplash.jpg
header_text: Judging book covers by their typography.
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/logo2.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
